<?php
namespace itseo\test;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-21 at 16:14:16.
 */
class FlashTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Flash
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Flash;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers itseo\test\Flash::test
     * @todo   Implement testTest().
     */
    public function testTest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers itseo\test\Flash::prepareTest
     * @todo   Implement testPrepareTest().
     */
    public function testPrepareTest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
