<?php
namespace itseo\test;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-21 at 16:14:18.
 */
class UrlLengthTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UrlLength
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UrlLength;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers itseo\test\UrlLength::test
     * @todo   Implement testTest().
     */
    public function testTest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers itseo\test\UrlLength::prepareTest
     * @todo   Implement testPrepareTest().
     */
    public function testPrepareTest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
