<?php
namespace itseo;

use itseo\test;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-21 at 16:14:15.
 */
class ItseoTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Itseo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Itseo("http://www.brainhardware.es/");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers itseo\Itseo::extractDomain
     * @todo   Implement testExtractDomain().
     */
    public function testExtractDomain()
    {
        $this->assertEquals("www.brainhardware.es", $this->object->extractDomain($this->object->target));
    }

    /**
     * @covers itseo\Itseo::createBaseUrl
     * @todo   Implement testCreateBaseUrl().
     */
    public function testCreateBaseUrl()
    {
        $this->assertEquals("http://www.brainhardware.es/", $this->object->createBaseUrl($this->object->target));
    }

    /**
     * @covers itseo\Itseo::extractDOM
     * @todo   Implement testExtractDOM().
     */
    public function testExtractDOM()
    {
        $this->assertInstanceOf("DOMDocument", $this->object->extractDOM($this->object->page_HTML));
    }

    /**
     * @covers itseo\Itseo::prepareTest
     * @todo   Implement testPrepareTest().
     */
    public function testPrepareTest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers itseo\Itseo::makeTest
     * @todo   Implement testMakeTest().
     */
    public function testMakeTest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
